#!/bin/bash

set -u
set -e

declare -A PROGRAM_TO_RESTART

PROGRAM_TO_RESTART=(
	["polybar"]="Bar (polybar)"
	["sxhkd"]="Window Key Manager (sxhkd)"
	["feh"]="Wallpaper (feh)"
	["bspwm"]="Window Manager (bspwm)"
)

prog_polybar="Bar (polybar)"
prog_sxhkd="Window Key Manager (sxhkd)"
prog_feh="Wallpaper (feh)"
prog_bspwm="Window Manager (bspwm)"

chosen=`rofi -i -dmenu <<- EOM
	$prog_polybar
	$prog_sxhkd
	$prog_feh
	$prog_bspwm
EOM`

case $chosen in
	$prog_polybar)
		pkill -USR1 -x polybar
	;;
	$prog_sxhkd)
		pkill -USR1 -x sxhkd
	;;
	$prog_feh)
		wallpapers="$XDG_DATA_HOME/wallpaper"
		bg_image=$(ls $wallpapers | rofi -dmenu)
		feh --bg-fill $wallpapers/$bg_image
	;;
	$prog_bspwm)
		./$XDG_CONFIG_HOME/bspwm/bspwmrc
	;;
esac


