#!/bin/bash

PACKAGE_MANAGER='pacman_program="sudo -u #$UID $HOME/.local/bin/yay --pacman powerpill" pacmatic'

info="View package info"
uninstall="Uninstall / Remove packages"
upgrade="Upgrade / Sync existing package"
switch="Home-manager Switch"

chosen=`rofi -i -dmenu <<- EOM
	$info
	$uninstall
	$upgrade
	$switch
EOM`



case $chosen in
	$info)
		PKG=$(pacman -Qq | rofi -dmenu)
		kitty sh -c "pacman -Qil $PKG | less"
	;;
	$uninstall)
		target=$(pacman -Qq | rofi -dmenu)
		kitty sh -c "$PACKAGE_MANAGER -Rsc $target"
	;;
	$upgrade)
		target=$(checkupdates | awk '{print $1}' | rofi -dmenu)
		kitty sh -c "$PACKAGE_MANAGER -S $target"
	;;
	$switch)
		kitty sh -c "cd $HOME && home-manager switch"
	;;
esac
