#!/bin/bash

bluetooth="Configure Bluetooth"
color_picker="Colour Picker"
emoji="Select Emoji"
screenshot_full_page="Screenshot Full"
screenshot_proof="Screenshot Proof"
screenshot_selection="Screenshot Selection"
song_next="Next Song"
song_play_pause="Toggle Music"
song_previous="Previous Song"
watch_ball="Watch Basketball"

chosen=`rofi -i -dmenu <<- EOM
	$bluetooth
	$color_picker
	$emoji
	$screenshot_full_page
	$screenshot_proof
	$screenshot_selection
	$song_next
	$song_play_pause
	$song_previous
	$watch_ball
EOM`

case $chosen in
	$open)
		rofi -show drun
	;;
	$song_previous)
		playerctl previous
	;;
	$song_next)
		playerctl next
	;;
	$song_play_pause)
		playerctl play-pause
	;;
	$lock)
		slock
	;;
	$kill_prog)
		prog_pid=$(ps -ef | rofi -dmenu | awk '{print $2}')
		kill -9 $prog_pid
	;;
	$color_picker)
		colour=$(chameleon)
		echo $colour | xsel --clipboard --input
	;;
	$screenshot_selection)
		maim -s $HOME/Dropbox/screenshots/$(date +%F-%T).png
	;;
	$screenshot_proof)
		maim -s $HOME/documents/proof/banking/$(date +%F-%T).png
	;;
	$restart_proc)
		rofi_restart
	;;
	$screenshot_page)
		maim $HOME/screenshots/$(date +%F-%T).png
	;;
	$watch_ball)
		mimeo https://sportsurge.net/#/groups/19
	;;
	$bluetooth)
		rofi_bt
	;;
	$emoji)
		rofi_emoji
	;;
	$prog_polybar)
		pkill -USR1 -x polybar
	;;
	$prog_sxhkd)
		pkill -USR1 -x sxhkd
	;;
	$prog_xwallpaper)
		wallpapers="$XDG_DATA_HOME/wallpapers"
		bg_image=$(ls $wallpapers | rofi -dmenu)
		xwallpaper --center $wallpapers/$bg_image
	;;
	$prog_bspwm)
		exec "$XDG_CONFIG_HOME/bspwm/bspwmrc"
	;;
esac


