#!/bin/bash

kill_prog="Kill process (top)"
lock="Lock Screen (slock)"
top="Process Manager (gotop)"
restart_computer="Restart / Reboot (systemd)"
shutdown_computer="Shutdown (systemd)"
prog_polybar="Relaunch Bar (polybar)"
prog_sxhkd="Relaunch Window Key Manager (sxhkd)"
prog_xwallpaper="Change Wallpaper (xwallpaper)"
prog_bspwm="Relaunch Window Manager (bspwm)"

chosen=`rofi -i -dmenu <<- EOM
	$lock
	$kill_prog
	$top
	$prog_polybar
	$prog_sxhkd
	$prog_xwallpaper
	$prog_bspwm
	$restart_computer
EOM`

case $chosen in
	$lock)
		slock
	;;
	$kill_prog)
		prog_pid=$(ps -ef | rofi -dmenu | awk '{print $2}')
		kill -9 $prog_pid
	;;
	$top)
		kitty sh -c "gotop"
	;;
	$restart_proc)
		rofi_restart
	;;
	$emoji)
		rofi_emoji
	;;
	$prog_polybar)
		pkill -USR1 -x polybar
	;;
	$prog_sxhkd)
		pkill -USR1 -x sxhkd
	;;
	$prog_xwallpaper)
		wallpapers="$XDG_DATA_HOME/wallpapers"
		bg_image=$(ls $wallpapers | rofi -dmenu)
		feh --bg-scale $wallpapers/$bg_image
	;;
	$prog_bspwm)
		./$XDG_CONFIG_HOME/bspwm/bspwmrc
	;;
	$restart_computer)
		systemctl reboot
	;;
	$shutdown_computer)
		systemctl poweroff
	;;
esac


