#!/bin/bash

PACKAGE_MANAGER='pacman_program="sudo -u #$UID $HOME/.local/bin/yay --pacman powerpill" pacmatic'

info="View package info"
orphaned="Remove orphaned packages"
uninstall="Uninstall packages"
upgrade="Upgrade existing package"

chosen=`rofi -i -dmenu <<- EOM
	$info
	$orphaned
	$uninstall
	$upgrade
EOM`



case $chosen in
	$info)
		PKG=$(pacman -Qq | rofi -dmenu)
		kitty sh -c "pacman -Qil $PKG | less"
	;;
	$uninstall)
		target=$(pacman -Qq | rofi -dmenu)
		kitty sh -c "$PACKAGE_MANAGER -Rsc $target"
	;;
	$upgrade)
		target=$(checkupdates | awk '{print $1}' | rofi -dmenu)
		kitty sh -c "$PACKAGE_MANAGER -S $target"
	;;
esac
