#!/bin/sh

is_mac() {
    [ "$(uname)" = "Darwin" ]
}

# Setup XDG Base Directory
# Having these exported ensures that programs are installed to the correct locations
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_DATA_HOME="$XDG_LOCAL_HOME/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

if is_mac; then
    # sh "$XDG_CONFIG_HOME/yadm/bootstrap.d/mac-defaults.sh"
    sh "$XDG_CONFIG_HOME/yadm/bootstrap.d/homebrew.sh"
fi

sh "$XDG_CONFIG_HOME/yadm/bootstrap.d/git.sh"
