[settings]
always_keep_download = false
always_keep_install = false
asdf_compat = false
disable_default_shorthands = false
disable_tools = []
experimental = false
jobs = 4
legacy_version_file = false
legacy_version_file_disable_tools = []
log_level = "INFO"
missing_runtime_behavior = "warn"
plugin_autoupdate_last_check_duration = 10080
raw = false
trusted_config_paths = []
verbose = false
yes = false

[tools]
ant = "1.10.10"
aria2 = "1.35.0"
carthage = "0.39.1"
cmake = "3.27.7"
direnv = "2.30.3"
fd = "8.7.0"
fzf = "0.38.0"
git = "2.42.0"
go = "1.21"
gradle = "8.4"
haskell = "9.2.1"
java = "openjdk-17"
jq = "1.6"
julia = "1.8.5"
just = "1.16.0"
kotlin = "1.6.10"
lazygit = "0.40.2"
make = "4.4.1"
maven = "3.9.0"
neovim = "0.9.0"
nodejs = "17.3.1"
pnpm = "7.27.0"
python = "3.11"
ripgrep = "14.0.0"
ruby = "3.1.0"
rust = "1.67.0"
shellcheck = "0.9.0"
shfmt = "3.6.0"
tree-sitter = "0.20.8"
yadm = "3.2.2"
zellij = "0.39.2"
