[settings]
always_keep_download = false
always_keep_install = false
asdf_compat = false
disable_default_shorthands = false
disable_tools = []
experimental = true
jobs = 4
legacy_version_file = false
legacy_version_file_disable_tools = []
plugin_autoupdate_last_check_duration = 10080
raw = false
trusted_config_paths = []
verbose = false
yes = false


[tools]
adr-tools = "3.0.0"
bat = "0.23.0"
cmake = "3.27.9"
direnv = "2.32.3"
exa = "0.10"
fd = "8.7.0"
fzf = "0.40.0"
gcloud = "426.0.0"
git = "2.42.0"
golang = "1.20"
grpcurl = "1.8.8"
helm = "3.11.0"
java = "openjdk-11"
jq = "1.6"
k6 = "0.47.0"
k9s = "0.27.4"
kubectx = "0.9.5"
maven = "3.9.0"
neovim = "0.9.0"
nodejs = "18.14.1"
python = "3.11.0"
ripgrep = "14.0.0"
shfmt = "3.7.0"
terraform = "0.14.3"
tfenv = "0.4.0"
tree-sitter = "0.20.8"
yadm = "3.2.2"
yarn = "1.22.19"
yq = "4.33.3"
zellij = "0.39.0"
minikube = "1.32.0"
deno = "1.38.0"
