#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

TOGGLE="/Users/vikramvenkataramanan/.config/yabai/.toggle_state"

if [ ! -e "$TOGGLE" ]; then
    touch "$TOGGLE"
    yabai -m config top_padding 50
else
    rm "$TOGGLE"
    yabai -m config top_padding 10
fi
