#!/bin/sh

TOGGLED="$XDG_CONFIG_HOME/yabai/.toggle_state"

if [ ! -e "$TOGGLED" ]; then
    touch "$TOGGLED"
    yabai -m config left_padding 550
else
    rm "$TOGGLED"
    yabai -m config left_padding 12
fi
