# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

# improves completions for various commands
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# fish-like autosuggestions
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.prompt-settings]
inline = "zstyle :prompt:pure:git:stash show yes"

[plugins.zsh-z]
github = "agkozak/zsh-z"

[plugins.pure]
github = 'sindresorhus/pure'
use = ['async.zsh', 'pure.zsh']

# keep last!
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
