# ---------------------------------------------------------------------------------------
# ---{ Brewfile } -----------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
#   This file lists some of the programs that I use on mac OSX
#
#   `brew bundle cleanup`               Will tell you how out of sync this file is
#   `brew bundle cleanup --force`       Remove stuff that are not in this file
#   `brew bundle`                       Install everything listed in this file
#
# ---{ Taps } ---------------------------------------------------------------------------
#
#   These are the packages reposititories that homebrew should look at
#

cask_args appdir: '/Applications'
cask_args fontdir: '/Library/Fonts'

# tap dance
tap 'aws/tap'
tap 'hashicorp/tap'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'koekeishiya/formulae'
tap 'ngrok/ngrok'
tap 'ankitpokhrel/jira-cli'

brew 'koekeishiya/formulae/skhd'
brew 'koekeishiya/formulae/yabai'

brew 'ankitpokhrel/jira-cli/jira-cli'
brew 'aria2'
brew 'asciinema'
brew 'aspell'
brew 'automake'
brew 'ca-certificates'
brew 'carthage'
brew 'coreutils'
brew 'csvkit'
brew 'curl'
brew 'diff-so-fancy'
brew 'editorconfig'
brew 'fastlane'
brew 'gcc'
brew 'gh'
brew 'gnu-getopt'
brew 'gnu-sed'
brew 'gnupg'
brew 'gnutls'
brew 'grep'
brew 'grpcurl'
brew 'hopenpgp-tools'
brew 'imagemagick'
brew 'libssh'
brew 'libusb'
brew 'libyubikey'
brew 'mitmproxy'
brew 'mprocs'
brew 'mysql'
brew 'neofetch'
brew 'nmap'
brew 'pass'
brew 'postgresql'
brew 'protobuf'
brew 'qemu'
brew 'redis'
brew 'rtx'
brew 'sheldon'
brew 'shellcheck'
brew 'syncthing'
brew 'trash'
brew 'tree'
brew 'vifm'
brew 'wget'
brew 'xdg-ninja'
brew 'ykman'
brew 'ykpers'

# server core stuff
brew 'ansible'
brew 'mariadb@10.2'

brew 'hashicorp/tap/vault'


cask 'font-ia-writer-mono'
cask 'font-iosevka'
cask 'font-iosevka-nerd-font'
cask 'font-jetbrains-mono'
cask 'font-monaspace'

# ---{ Casks } --------------------------------------------------------------------------
#
#   `brew cask` is an extension to `brew` that allows for the management of graphical
#   applications through the cask project
#

cask 'alfred'
cask 'alt-tab'
cask 'appcleaner'
cask 'barrier'
cask 'beardedspice'
cask 'burp-suite'
cask 'caffeine'
cask 'charles'
cask 'cyberduck'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'gpg-suite-no-mail'
cask 'hiddenbar'
cask 'insomnia'
cask 'itsycal'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'keybase'
cask 'meetingbar'
cask 'ngrok'
cask 'obsidian'
cask 'postman'
cask 'raycast'
cask 'spotify'
cask 'sublime-text'
cask 'tableplus'
cask 'ubersicht'
cask 'visual-studio-code'
cask 'wezterm'
cask 'wireshark'
cask 'xquartz'

# ---------------------------------------------------------------------------------------
