#! /bin/sh

TERMINAL="kitty"
MAIN_BAR="example"

# Just in case xinit missed them
pgrep -x sxhkd      > /dev/null || sxhkd &
pgrep -x polybar    > /dev/null || polybar $MAIN_BAR &
pgrep -x bspswallow > /dev/null || $XDG_CONFIG_HOME/scripts/bspswallow &

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor eDP1  -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
for m in $(bspc query --monitors)
do
	bspc monitor "$m" --reset-desktops I II III IV V VI VII
done

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding 		30

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule --add Spotify desktop='^2'
bspc rule --add Discord desktop='^3'
bspc rule --add Signal desktop='^3'
bspc rule --add Caprine desktop='^3'

bspc rule --add feh state=fullscreen
bspc rule --add Zathura state=tiled
bspc rule --add Emacs state=tiled

bspc rule --add Gimp desktop='^8' state=floating follow=on
bspc rule --add 'Tor Browser:Navigator' state=pseudo_tiled private=on

bspc rule --add dropdown sticky=on state=floating hidden=on
bspc rule --add filemanager sticky=on state=floating hidden=on
$TERMINAL --class dropdown &
$TERMINAL --class filemanager vifm $HOME &

