#! /bin/sh

TERMINAL="kitty"
MAIN_BAR="example"

# Just in case xinit missed them
pgrep -x sxhkd   > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar $MAIN_BAR &

# bspc monitor eDP1  -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 	30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Spotify desktop='^2'
bspc rule -a Discord desktop='^3'
bspc rule -a Signal desktop='^3'
bspc rule -a Caprine desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc rule -a dropdown sticky=on state=floating hidden=on
bspc rule -a filemanager sticky=on state=floating hidden=on
$TERMINAL --class dropdown &
$TERMINAL --class filemanager vifm $HOME &
