theme = "catppuccin_mocha"

[editor]
mouse = true
line-number = "relative"
auto-save	= true
auto-pairs = true
auto-completion = true

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "none" #"all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.file-picker]
hidden = false

[keys.insert]
j = { j = "normal_mode" }

        